Tickets/dm 15348
lsst-dm/dmtn-091 pull request #1
Opened 2018-08-15 21:58 UTC by wmwv

Defines CI, SMALL, MEDIUM, LARGE datasets.

2018-08-21 00:15 UTC, kfindeisen requested changes
I found the document a bit hard to understand because it reads like a set of notes rather than a report. In addition to the specific lines I've commented, I found the goals for the different size classes a bit vague (e.g., "integrated testing" vs. "verification" vs. "quantitative performance"). Could you expand to a few sentences about what is and isn't being covered at each level?

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +        - ~Coadd~
Why the `~`? Are these approximate coadds?

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +        - Allow checks for reasonable:
What's the difference between this test and "reasonable ranges of" in CI?

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +        - Verify DIA runs
This seems redundant with "Verify that DIA works". Is this a formal process thing?

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +            - Fraction of CCDs successfully processed
I would have thought that CI datasets would be vetted for "known good" data, and that we can therefore expect all observations to be successfully processed. Is this something we want to deal with at the CI scale? You mention "robustness" under medium-scale datasets...

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +The current Jenkins AWS solution has a much smaller number of available cores than the NCSA Verification Cluster.  The limitations imposed by that mean that a more restricted set of minimal data will
How do the capabilities of Jenkins compare to what you're requiring for CI? (It might also help to explicitly say in the CI section that you don't mean Jenkins or Travis).

I wouldn't consider "15 minutes on 16 cores" an onerous requirement for a laptop run. In fact, the running time would be dominated by updating the Stack...

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +      2. testing of ingestion of DRP data.
Not clear what you mean here. Are you saying that the data might not be useable?

Also, this doesn't format correctly in the compiled page. I think you need a blank line before "1."

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +      - Takes several hours when running on only a few nodes.
If it takes several hours despite access to multiple nodes (I assume this means at least a dozen cores), is it actually CI-sized by your definition above?

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +        https://github.com/lsst/ap_verify_ci_hits2015
It's not just specific fields: the data were also shrunk by using only 3 visits and 2 ccds per visit.

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
> +      - ISR is not performed.
Might want to say what is performed; as far as I know DIA isn't exercised either.

2018-08-21 00:15 UTC, kfindeisen commented on index.rst
>  :tocdepth: 1
This got corrupted somehow; maybe it needs to be at the start of the file rather than the end?

Likewise, the "This technote is not yet published" warning is not very useful at the end of the document. 😉

2018-08-22 12:39 UTC, wmwv commented
Thanks for the comments, @kfindeisen.

It is indeed more of a set of internal notes rather than a report.  I talked things over with @SimonKrughoff and we'll incrementally merge to master to circulate among a small team, but it's certainly true that this won't be meant for wider distribution until it has more narrative and context.

I'll go through and take your comments to improve the current version, and then continue working on future branches to bring this document closer to converging to something more widely useful.

2018-08-22 13:19 UTC, wmwv commented on index.rst
> +The current Jenkins AWS solution has a much smaller number of available cores than the NCSA Verification Cluster.  The limitations imposed by that mean that a more restricted set of minimal data will
I believe Jenkins is currently 4-8 cores.  The `validation_data_hsc` daily runs are done on a special medium scale node.

The longer-term plan is that CI is done at NCSA, which will have more easily deployed >16-core nodes for CI.

And yes, you're right that the CI-scale, even under the NCSA full capabilities should be runnable by a developer on their individual machine.  I'll add that to Requirements and update the "Jenkins vs. NCSA" discussion.

And thanks for prompting me to think that I should also call out the build vs. test part to clarify that the time requirements are meant to be just the science pipelines part.

2018-08-22 13:21 UTC, wmwv commented on index.rst
> +            - Fraction of CCDs successfully processed
That's a good point.  Currently 1-2 CCDs of the `validation_data_decam` set are expected to fail.  But I agree that we should change that so that CI should always pass and either SMALL or MEDIUM catches edge cases.  I wrote this under MEDIUM so I'll keep it there, but I'm a bit ambivalent.

2018-08-22 13:43 UTC, wmwv commented on index.rst
> +      2. testing of ingestion of DRP data.
I meant that the data weren't being currently ingested.  But I realize I'm mixing implementation and dataset definition.  I've removed the ingestion line.

2018-08-22 13:47 UTC, wmwv commented on index.rst
> +      - Takes several hours when running on only a few nodes.
You're right, despite the name, this is clearly SMALL in the definition above, and in use.  It's not part of the basic CI, but it is used by developers to check that things still work when going all the way through to coaddition.

2018-08-22 13:50 UTC, wmwv commented on index.rst
> +      - ISR is not performed.
DIA isn't part of the requirements for a CI-scale dataset.  I've added a note to the list to explicitly load this into the reader's mind again.

2018-08-22 13:50 UTC, wmwv commented on index.rst
>  :tocdepth: 1
Yes, thank you.  I've reread through the template in `index.rst` and re-ordered things hopefully more correctly.

2018-08-22 14:06 UTC, merged

2018-08-22 15:20 UTC, wmwv commented
To complete the Jenkins answer above: I believe the current `ci_hsc` and `validation_data_hsc` Jenkins runs are using AWS `m4.xlarge`:  4 cores, 16 GB.

2018-08-22 18:08 UTC, kfindeisen commented on index.rst
> +The current Jenkins AWS solution has a much smaller number of available cores than the NCSA Verification Cluster.  The limitations imposed by that mean that a more restricted set of minimal data will
The new text still implies that the CI datasets should not be run on Jenkins. Was that the intent?

2018-08-22 18:11 UTC, kfindeisen commented on index.rst
> +      - ISR is not performed.
Ah, I didn't understand that you were using `~` to mean "not" in the earlier version. Objection withdrawn.

2018-08-22 18:13 UTC, wmwv commented on index.rst
> +The current Jenkins AWS solution has a much smaller number of available cores than the NCSA Verification Cluster.  The limitations imposed by that mean that a more restricted set of minimal data will
Yesish.  These are future-focused definitions.